### ISSUE TITLE
Realtime events on WebGL 

### ISSUE THREAD

**Issue by vitaliyMalishchuk** [SrejonKhan/FirebaseRestClient#2]
Hi, I am trying to add real-time events to my project, like ChildChanged or ValueChanged, and in the editor, everything works well, but in a build(WebGL), it doesn't return any data. Please advise me if there is some workaround or fix?
Thanks.

**Comment by SrejonKhan** [comment]
I've looked into it. The problem is not related to CORS as I thought at the very first moment. 

In the Network tab, WebGL sends the request to firebase correctly with proper headers. It also waits to receive event data. Maybe it's a limitation of UWR or WebGL (which I don't think so, as the browser is capable of handling SSE).

However, I will try-catch a few workarounds for it. I will keep updating if I fix or find any workaround. 

Thanks for using FRC and I really appreciate your interest.

**Comment by SrejonKhan** [comment]
I hope it serves. 

**What happened I think -** 
Unity uses the browser's `fetch` API in WebGL for UnityWebRequest. Firebase endpoints for child events are SSE Protocol supported (there is no special endpoint, every endpoint supports SSE Protocols), and the only way to implement child events is by listening to SSE. 

Generally, `fetch` API doesn't work for SSE (Server-Sent Events). The browser has a different class for SSE, which is `EventSource`. So, I wrote a JsLib that implements `EventSource` and established two-way communication with Game Code and Browser (to receive callbacks). 

If you are interested, you can check [changes](https://github.com/SrejonKhan/FirebaseRestClient/commit/f94bed48dfaca9181d57f1517a22d30f180c11d7) here.

Thanks for using FRC.

**Comment by vitaliyMalishchuk** [comment]
Thank you!
